### ISSUE TITLE
Consolidate multiple summary report

### ISSUE THREAD

**Issue by priya-dsp** [artilleryio/artillery#2478] opened 2024-02-06 06:13 UTC
When we run multiple yamls either sequentially or parallelly, seperate summary reports are getting generated. Instead of having multiple reports, we need one single report. How to combine or generate single report for multiple yamls?

If we generate combined summary report , we are getting values picked up from recent report for the below parameters:
http.codes.200
http.downloaded_bytes
http.requests
http.responses
plugins.expect.ok
plugins.expect.ok.contentType
plugins.expect.ok.equals
plugins.expect.ok.hasProperty
vusers.completed
vusers.created
vusers.failed

I'm not using Artillery pro. 
<img width="580" alt="Combined report" src="https://github.com/artilleryio/artillery/assets/159108432/0bac4541-794e-4eb0-a5a0-a305539d98bc">

**Comment by hassy** [comment] 2024-02-06 21:46
closing this as duplicate of #2479

**Closed by hassy** 2024-02-06 21:46 UTC
