### ISSUE TITLE
ArtilleryError on Lambda deployment

### ISSUE THREAD

**Issue by mplaul** [artilleryio/artillery#2543] opened 2024-03-05 13:13 UTC
Version info:

```
VERSION INFO:

Artillery: 2.0.0-30
Node.js:   v20.5.1
OS:        darwin
```

Running this command:

```
./packages/artillery/bin/run run --platform aws:lambda --platform-opt region=eu-west-1 --count 60 configs/lt-221.yml
```

I expected to see this happen:

A load test with 60 lambda workers running the specified config

Instead, this happened:

```
[ebceaa13-cdc2-46ee-904c-c835e471ed83]: A Lambda function has exited with an error. Reason: ArtilleryError
{
  stdout: "worker error, id: 1 TypeError [Error]: Cannot read properties of undefined (reading 'plugins')\n" +
    '    at prepare (/var/task/node_modules/artillery/lib/platform/local/worker.js:114:51)\n' +
    '    at async MessagePort.onMessage (/var/task/node_modules/artillery/lib/platform/local/worker.js:50:5)\n',
  stderr: ''
}
```

Files being used:

```
config:
  target: <redacted>
  phases:
    - duration: 60
      arrivalRate: 20
      name: Load Test
scenarios:
  - flow:
      - loop:
          - post:
              url: "/"
              json:
                {
                  "id": "{{ $randomString(10) }}",
                  “event”: "7d8b1631-faeb-4b47-926e-077da7ed4f7c",
                }
        count: 100
```

**Comment by bernardobridge** [comment] 2024-03-06 10:40
Hey @mplaul 👋 

Thanks for reporting the issue. For anyone else reading this, if you're facing this issue you'll need to upgrade Artillery preferably to latest (`v2.0.7`).

_Note: This sort of breaking change will no longer happen with any version after `v2.0.1`, as it was a bug in how we managed dependant packages that was solved with the `v2.0.1` release._

**Comment by mplaul** [comment] 2024-03-06 15:13
Thanks @bernardobridge. Upgrading to 2.0.7 worked.

**Comment by mirao** [comment] 2024-03-08 14:41
We got the same issue after an upgrade of Playwright to 1.42.1 in our [CodeceptJS](https://codecept.io/) project.
From some reason the upgrade of Playwright caused also an upgrade of some Artillery components. Then when we started an Artillery test, it failed with:
```
$ npx artillery run -e dev --output output/artillery.json load-test.yml
worker error, id: 1 TypeError [Error]: Cannot read properties of undefined (reading 'plugins')
```
Upgrade of Artillery from 2.0.0-34 to 2.0.7 helped :heavy_check_mark:

**Comment by mirao** [comment] 2024-03-09 10:58
> From some reason the upgrade of Playwright caused also an upgrade of some Artillery components.

It's not caused by upgrade of Playwright, but by the process `pnpm update` itself.
It seems that once Artillery 2.0.7 was released with some updated components (e.g. `artillery-plugin-publish-metrics` 2.12 => 2.13 etc.), the components were updated by `pnpm` (by chance during update of Playwright) and then they become incompatible with our installed Artillery 2.0.0-34)

**Comment by sahmeepee** [comment] 2024-05-07 16:31
Is there a working method of installing versions of Artillery 2.0.0-33 or earlier? I'm trying to work out at what point this bug was introduced: https://github.com/artilleryio/artillery/issues/2115
According to the issue it was between v2.0.0-7 and 2.0.0-36 (inclusive) so I would like to be able to bisect those versions to narrow it down.

**Closed** 2024-11-08 03:40 UTC
