### ISSUE TITLE
Get request scenario never ends.

### ISSUE THREAD

**Issue by TheFurnace** [artilleryio/artillery#1799] opened 2023-02-01 21:10 UTC
Version info: 
```
VERSION INFO:

Artillery: 2.0.0-29
Node.js:   v19.5.0
OS:        win32
```

Running this command: 
```
artillery run --output report.json .\ddos.yaml
```

I expected to see this happen:

I expected the script to end.

Instead, this happened:

```
Phase started: unnamed (index: 0, duration: 1s) 16:08:55(-0500)

Phase completed: unnamed (index: 0, duration: 1s) 16:08:56(-0500)

--------------------------------------
Metrics for period to: 16:09:00(-0500) (width: 0.278s)
--------------------------------------

http.codes.200: ................................................................ 1
http.codes.301: ................................................................ 1
http.request_rate: ............................................................. 2/sec
http.requests: ................................................................. 2
http.response_time:
  min: ......................................................................... 28
  max: ......................................................................... 56
  median: ...................................................................... 27.9
  p95: ......................................................................... 27.9
  p99: ......................................................................... 27.9
http.responses: ................................................................ 2
vusers.created: ................................................................ 1
vusers.created_by_name.0: ...................................................... 1


- 
```

Files being used:
```
./ddos.yaml
config:
  target: "https://google.com"

scenarios:
  - flow:
    - get:
        url: "/"
```

**Comment by murad-khafizov** [comment] 2023-02-03 12:12
The same for me. Something is wrong with the latest version (2.0.0-29). Downgrade helps.

**Comment by rawpixel-vincent** [comment] 2023-02-07 04:51
same here, using version `2.0.0-22` fix the issue

**Comment by harsh-sri** [comment] 2023-02-09 14:52
same with me with the latest version

**Comment by hassy** [comment] 2023-02-14 14:45
thanks all, looking into it

**Comment by hassy** [comment] 2023-02-14 14:46
@rawpixel-vincent @harsh-sri @murad-khafizov is it happening with any other URLs other than google.com for you?

**Comment by murad-khafizov** [comment] 2023-02-14 14:48
I've never tried google.com actually, it happed with a couple of other websites

**Comment by rawpixel-vincent** [comment] 2023-02-14 15:44
Found something interesting, I couldn't reproduce the issue with some scenario where I used to have that problem.
I've tested those with the `2.0.0-29` and it didn't hang.

But I did update those scenario to use the plugin `metrics-by-endpoint:` with `useOnlyRequestNames` option to true

I removed that plugin from my scenario and the issue is back, with 2.0.0-29 it hangs after the first tests is completed, (if I press ctrl+c, it does exit and run the next test) - and it shows some warning `Warning: multiple batches of metrics for period 1676388890000` before hanging forever

with 2.0.0-22 the same test finish properly without warning.

output with 2.0.0-29
<img width="662" alt="Screenshot 2023-02-14 at 22 36 35" src="https://user-images.githubusercontent.com/22284209/218786421-1acdeca8-c9e3-44cd-b428-d48999b32fba.png">

with 2.0.0-22 (the next test started)
<img width="708" alt="Screenshot 2023-02-14 at 22 43 28" src="https://user-images.githubusercontent.com/22284209/218786589-5e00d9a1-6987-43b5-b2d2-4cb925c311c6.png">

my test script simply loop on a list of given TEST_NAMES
```
for T in $TEST_NAMES; do
  yarn artillery run --output=$DIR/reports/$T-report.json tests/$T.yaml || true;
  yarn artillery report --output=$DIR/reports/$T-report.html $DIR/reports/$T-report.json || true;
  sleep 2;
done
```

**Comment by hassy** [comment] 2023-02-17 14:22
Thanks for those details @rawpixel-vincent! What version of Node.js is that? and do you have any endpoints that may return a 3xx code in that test?

So far I've tracked down the issue to the code here:

https://github.com/artilleryio/artillery/blob/main/packages/core/lib/engine_http.js#L752-L757

It seems that unless there's a `'data'` event handler, the `'end'` event handler doesn't fire properly for requests which are part of a redirect chain (e.g. in the original comment, https://google.com returns a redirect). The reason it works with the plugin is because loading the plugin makes the HTTP engine set `data` event handler.

**Comment by rawpixel-vincent** [comment] 2023-02-17 14:34
Hello, it's node 18.x
There doesn't seems to be any redirect but i set a timeout limit and there's also an http basic Auth.
Anyway your explanation makes sense👍

**Comment by hassy** [comment] 2023-02-17 19:15
Thanks @rawpixel-vincent! I'll need to dig a bit deeper into this to try to figure out when exactly it broke and what's causing it. My current understanding is that this only happens when redirects are involved, but if your tests don't have any redirects I'll need to keep looking.

**Comment by hassy** [comment] 2023-03-17 16:27
should be fixed on `main` now

**Comment by honarkhah** [comment] 2023-05-15 09:32
I have the same problem with the official docker image; when I enable debug, it will close, but otherwise, it will keep the process running forever!

**Closed** 2023-07-10 09:28 UTC
Labels: bug
