### ISSUE TITLE
Playwright-Artillery Test-integration

### ISSUE THREAD

**Issue by srivishal1** [artilleryio/artillery#1710] opened 2022-12-02 11:29 UTC
### Discussed in https://github.com/artilleryio/artillery/discussions/1473

<div type='discussions-op-text'>

<sup>Originally posted by **ChetanKB** June  7, 2022</sup>
Hi all,
I am Trying to Execute the test.spec.js file Via the artillery, the test.spec.js contains all the tests which I want to execute via the artillery engine but to execute javascript, I need to mention the function name in the YAML file But my Javascript doesn't have any function name so is there any way available to execute the multiple tests via artillery engine.

### Here is The code of my spec.js :

```
const { test, expect } = require('@playwright/test');

let d = new Date();
let timestamp = d.getTime();

test.describe.parallel('group', () => {

  test('test-1', async ({ page }) => {


    await page.goto('https://en.wikipedia.org/wiki/Main_Page');

    await page.locator('[placeholder="Search Wikipedia1"]').click();

    await page.locator('[placeholder="Search Wikipedia"]').fill('testing');
    // Press Enter
    await Promise.all([
      page.waitForNavigation(),
      page.locator('[placeholder="Search Wikipedia"]').press('Enter')
    ]);
   // await page.screenshot({ path: './screenshots/test-1-' + timestamp + '.png' });
    // Go to https://en.wikipedia.org/wiki/Main_Page
    await page.goto('https://en.wikipedia.org/wiki/Main_Page');

  });

  test('test-2', async ({ page }) => {

    
  await page.goto('https://en.wikipedia.org/wiki/Main_Page');

  await page.waitForLoadState();

  await page.locator('[placeholder="Search Wikipedia"]').click();

  await page.locator('[placeholder="Search Wikipedia"]').fill('automation');

  await Promise.all([
      page.waitForNavigation(),
      page.locator('[placeholder="Search Wikipedia"]').press('Enter')
    ]);
//await page.screenshot({ path: './screenshots/test-2-' + timestamp + '.png' });

  await page.locator('text=Main page').click();
  await expect(page).toHaveURL('https://en.wikipedia.org/wiki/Main_Page');


  });
})
```

### This is the Project Structure:

![issue](https://user-images.githubusercontent.com/53107584/172354113-274edb0b-8e0e-4a10-a6d7-79a62c409bd9.png)

</div>

**Comment by hassy** [comment] 2022-12-04 15:00
this seems to be just a duplicate of the original post in the linked discussion, closing

**Closed by hassy** 2022-12-04 15:00 UTC
