### ISSUE TITLE
installing dependencies in lambda not working

### ISSUE THREAD

**Issue by vbpatel73** [artilleryio/artillery#1607] opened 2022-09-22 19:14 UTC
i am getting below error in lambda
2022-09-22T18:46:06.310Z	5049e138-343f-49a4-b80a-986569601d7b	ERROR	internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/var/task/node_modules/.bin/artillery'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

when i check in lamda i did not find any node modules and when i debug it i found 
this line giving me error 
**artillery.log('    - Installing dependencies')
    const { stdout, stderr, status, error } = spawnSync('npm', ['install'], {cwd: dirname});**

**Comment by hassy** [comment] 2022-09-27 10:03
thanks @vbpatel73 - does the system have `npm` installed?

**Comment by hassy** [comment] 2022-10-28 19:56
unable to reproduce, closing

**Closed by hassy** 2022-10-28 19:56 UTC
